server:
  port: 8090
  server: tomcat.uri-encoding=utf-8

spring:
    datasource:
        name: com.mysql.jdbc.Driver
       # url: jdbc:mysql://118.190.39.192/fun?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&&useOldAliasMetadataBehavior=true
       # username: fun
       # password: havefun888
       #生产
        url: jdbc:mysql://118.190.39.192/fun?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&&useOldAliasMetadataBehavior=true
       #测试
        #url: jdbc:mysql://39.105.211.164/fun?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&&useOldAliasMetadataBehavior=true
        username: fun
        password: havefun888



        # 使用druid数据源
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5

    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 5000


mybatis:
  mapperLocations: classpath*:mapper/*.xml

# Redis数据库索引（默认为0）
   #spring.redis.database= 0
# Redis服务器地址
   #spring.redis.host=localhost
# Redis服务器连接端口
   #spring.redis.port=6379
# Redis服务器连接密码（默认为空）
    #spring.redis.password=
# 连接池最大连接数（使用负值表示没有限制）
    #spring.redis.pool.max-active=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
    #spring.redis.pool.max-wait=-1
# 连接池中的最大空闲连接
    #spring.redis.pool.max-idle=8
# 连接池中的最小空闲连接
   #spring.redis.pool.min-idle=0
# 连接超时时间（毫秒）
   #spring.redis.timeout=0



